### PR TITLE
Added Al-Khaser console parameters for test enabling

### PR DESCRIPTION
**Pull request by Haimasker**
Added posibility to enable checks groups in console.
Helpful for software using al-khaser or for writing al-khaser running scripts.
---
Examples:
* `al-khaser_x64.exe` runs al-khaser with default checks (as they were defined before)
* `al-khaser_x64.exe --check TLS` runs al-khaser only with TLS checks
* `al-khaser_x64.exe --check KVM --check GEN_SANDBOX` runs al-khaser KVM and GEN_SANDBOX checks

### CODE REVIEW

**Comment by LordNoteworthy** [comment]
Hello @Haimasker 

Thanks for your PR ! looks good to me, can you keep the values for the platform toolset to `v143`.

**Comment by LordNoteworthy** [comment]
No worries, once you fix that, happy to merged it :)

**Comment by Haimasker** [comment]
> No worries, once you fix that, happy to merged it :)

It's already fixed.

**Comment by LordNoteworthy** [comment]
Thanks a lot for your contribution ! Now I don't have to manually change code to enable/disable some checks :)

**Pull request merged**
