### PR TITLE
Add some checks

### PR DESCRIPTION
**Pull request by lurumdare**
from here https://github.com/rajrakeshdr/soldier_win/blob/master/Soldier/antivm.h

### CODE REVIEW

**Comment by lurumdare** [comment]
`LNK2019: unresolved external symbol ntohl referenced in function`

need add `Ws2_32.lib`

**Comment by LordNoteworthy** [comment]
Hello,

We have already support for :

- NtQueryInformationProcess (ProcessDebugPort)
- ProcessHeap (Flags)
- ProcessHeap (ForceFlags)

Look at anti-debug section in our README.

Some notes:

- Try to push each technique in a separate PR.
- Use instrincs functions as much as you can so you don't have to inline for both x32 and x64.

**Comment by lurumdare** [comment]
> * Do not change the SDK version, it breaks our CI.

Can you not change it? On the computer, another version is installed and I do not want to put your

**Comment by lurumdare** [comment]
@LordNoteworthy refactor my PR 
and add those techniques that you need. Thanks.

**Comment by hfiref0x** [comment]
Using things through assembler does not make them magically work in a different way or better than already in this particular case. While I understand your attempt to do effort in this project it doesn't mean it should become your pet project for testing all the github garbage you can find.

**Comment by lurumdare** [comment]
@hfiref0x i think project is dead in the bud. Judge. ScyllaHide on clear system bypass all* checks.

**Comment by Mattiwatti** [comment]
@lurumdara How do you think ScyllaHide managed to bypass these detections?

ScyllaHide is regularly tested on tools like Al-khaser to make sure it works and bypasses known techniques. This is literally one of the stated uses in Al-khaser's README. So claiming the project is dead is the precise opposite of the truth.

**Comment by lurumdare** [comment]
@Mattiwatti what detections?

**Comment by Mattiwatti** [comment]
The ones listed in your screenshot...

**Comment by hfiref0x** [comment]
@lurumdare
You can judge whatever you want. Honestly I don't understand what you expect from open-source detector tool against open-source hiding tool. How do you think it gonna work?

Aside from this PR. As mentioned above the majority of these commits already implemented in this tool and making the same code just in assembler doesn't make it better or stealthy. In fact it just ruins x64 compilation because inline assembly is not allowed here.

And this one https://github.com/LordNoteworthy/al-khaser/pull/179/commits/55e9cfb5ad2b2bf1d90213a4543a792671f73aa8 makes 0 sense. It already implemented as https://github.com/LordNoteworthy/al-khaser/blob/3bac6f768260bc425952ffa626904b1e83b1a4bc/al-khaser/TimingAttacks/timing.cpp#L151 with intrinsics and work better while this concept code is only FP generator.

https://github.com/LordNoteworthy/al-khaser/pull/179/commits/fa829c6f8cd47de65d2d65dff84527de6b24c557
This one, it is a ThreadHideFromDebugger and it is implemented here
https://github.com/LordNoteworthy/al-khaser/blob/c1c491df29451837807965f9fb13a50a018c35d9/al-khaser/AntiDebug/NtSetInformationThread_ThreadHideFromDebugger.cpp#L14
Notice the difference how it implemented - it actually not simple call this function but make an analytics of results - is what your code missing completely.

https://github.com/LordNoteworthy/al-khaser/pull/179/commits/d407d37e7ae6584740fac4fbc95abc21645e9e6c
This one, it is implemented here https://github.com/LordNoteworthy/al-khaser/blob/3bac6f768260bc425952ffa626904b1e83b1a4bc/al-khaser/AntiDebug/HardwareBreakpoints.cpp#L12
Notice another difference - all these methods have _explanation_ not simple copy-pasted from somewhere.

Be creative and do something that is not published here or in some random Chinese repo full of x86 assembly trash.

**Comment by gsuberland** [comment]
I have to agree with @hfiref0x here (barring the "random Chinese repo" comment which I think is unnecessarily inflammatory).

Duplicating techniques in the tool is unnecessary, particularly with less readable and non-portable assembly versions. Expecting open source VM detection techniques to remain unnoticed by creators of open source VM detection evasion tools is also futile, and there's no reason (or value) in us engaging in a tit-for-tat arms race with them.

If you have any new techniques to add that are not listed in the readme (and please search the code too!) then we do welcome PRs, preferably with one feature per PR so that useful new techniques can be reviewed and accepted quickly without getting complicated or slowed down by problems with other additions.

**Pull request closed without merging**
