### PR TITLE
This will build and upload binaries 

### PR DESCRIPTION
**Pull request by graysuit**
Binaries would be helpful for testing in a hurry.
And also, it won't trigger common user fear about virus, because it is build using source code in front of them. lol

Regards

### CODE REVIEW

**Comment by gsuberland** [comment]
I'm not sure I follow. Is this for Azure? What's the use-case here?

To be clear: we generally don't host the binaries on GitHub because when we do the repo gets flagged as malicious by Google and Chrome users get the very annoying red warning screen.

**Comment by graysuit** [comment]
Its official GitHub workflows and can be use as VPS, RDP etc to compile, test, upload or run binaries. 
It will be going to help you:

from: https://github.com/LordNoteworthy/al-khaser/issues/123#issue-342685399
```
For continuous integration, it would be nice to integrate TravisCI or Appveyor to Github, so we can build and run some tests when somebody make commits/PR. I did a quick search and found out Appveyor to be suitable for our needs, they offer free Windows VM with different VS versions where we can do our builds/tests.
```
This follows:
- build and run some tests when somebody make commits/PR
- you can test with different VS versions 

The current sample build code and upload the executable.
You can edit the code to NOT upload exe.

See how it works:
**logs :** https://github.com/learning-hide/al-khaser/runs/2979384850?check_suite_focus=true
**Binaries:** https://github.com/learning-hide/al-khaser/actions/runs/996520871
**workflows:** https://github.com/learning-hide/al-khaser/actions

**Comment by LordNoteworthy** [comment]
@gsuberland this can replace the current CI platform (Appveyor) which builds the binary using github actions (Github own CI/CD platform). I was thinking anyway to move to them as they integrate pretty nicely with Github. At the current stage, they only offer VMs, so we're still our of luck to run hypervisors on them to test al-khaser correctly, but you can run your own custom runner, you basically just download a small binary and run it on your own server, then it can start receiving jobs.

Thanks @graysuit for your PR. This looks fine to me, the only problem is that we need to encrypt the artifacts with a password, as we want to avoid google blacklisting our Github repo again. @gsuberland If we zip with a pwd the binaries, could it help ?

Few suggestions:

- `on: [push]`, worth to add also on `pull-request`.
- `runs-on: windows-latest`, better hard code the OS as when MS will release a new version, it might break the build, just replace it with  `windows-2019`
- Add another step to zip the file with a password, the VMs already have several [software ](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) pre-installed, you can use 7-zip and put a custom password, not `infected` or `malware` as Google malware heuristic engine tries to be smart and might try those common passwords. Or you can look for an action that does that, up to you.

**Comment by graysuit** [comment]
encryption with 7zip always bypass anti's.
ok, now you can check the PR.

**Comment by gsuberland** [comment]
My bad, saw this PR without context and was confused. Good idea, thanks @graysuit for the work :)

**Comment by LordNoteworthy** [comment]
Thanks @graysuit. Can you quash your commits to a single one so we keep a nice commits history.

You have 11 commits, `n` will be 11.

image

And then git push -f

Cheers.

**Pull request closed without merging**
